-- CREATE DATABASE tgclient;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE message (
    id SERIAL PRIMARY KEY,
    uuid UUID NOT NULL UNIQUE,
    message JSONB,
    chatid BIGINT NOT NULL,
    groupid BIGINT,
    firstmessageid BIGINT,
    time_creation TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS userstat (
    id SERIAL PRIMARY KEY,
    chatid BIGINT NOT NULL UNIQUE,
    bayan JSONB NOT NULL,
    time_creation TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    last_update TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS errors (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  chatid BIGINT NOT NULL UNIQUE,
  userid BIGINT NOT NULL,
  count INT,
  time_creation TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  last_update TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);


CREATE OR REPLACE FUNCTION update_last_update_column()
RETURNS TRIGGER AS $$
BEGIN
   NEW.last_update = CURRENT_TIMESTAMP;
   RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_userstat_last_update
BEFORE UPDATE ON userstat
FOR EACH ROW
EXECUTE FUNCTION update_last_update_column();
